### ISSUE TITLE
Create database on server

### ISSUE THREAD

**Issue by kenneth-bolivar-castro** [kvnABC/PRACTICE#2]
We should create a database into a server, we should be extra carefully to don't share credentials here.

**Comment by kvnABC** [comment]
Im very carefully but i dont know how do it because i cant see something to upload or write code, need your help here

**Comment by kenneth-bolivar-castro** [comment]
@kvnABC login into server:
https://am.greengeeks.com/home/

Then click to "cPanel Login", it will open another tab where you can find "databases" options,
![screenshot from 2017-04-05 13-15-41](https://cloud.githubusercontent.com/assets/3356086/24722713/04500df8-1a02-11e7-807a-ccbe4a695f21.png)

Once there, click to MySQL Databases option, then you should be able to create the database,
![screenshot from 2017-04-05 13-16-37](https://cloud.githubusercontent.com/assets/3356086/24722758/3531ea04-1a02-11e7-9f45-0fb661a8e6df.png)

Then you need to create a new MySQL user in order to manage the new database,
![screenshot from 2017-04-05 13-17-42](https://cloud.githubusercontent.com/assets/3356086/24722785/51e8d4fa-1a02-11e7-8ca6-fa154bffc5a1.png)

Right after, you should include new user reference to the new database just created,
![screenshot from 2017-04-05 13-18-23](https://cloud.githubusercontent.com/assets/3356086/24722828/6b5b4814-1a02-11e7-94e1-32074f2adc93.png)

It should be good enough to create this new database, then go back to Panel where you can see all "databases" options, and click to "phpMyAdmin" and choose your new database and click to "Import" tab,
![screenshot from 2017-04-05 13-21-21](https://cloud.githubusercontent.com/assets/3356086/24722956/d4f56fc0-1a02-11e7-83df-749cf51c0e59.png)

Right there, you only need to upload your [database file](https://github.com/kvnABC/PRACTICE/blob/master/DATABASE.sql) and hit import, be sure you remove the following statements,
https://github.com/kvnABC/PRACTICE/blob/master/DATABASE.sql#L3-L5

**Comment by kenneth-bolivar-castro** [comment]
@kvnABC any news?

**Comment by kvnABC** [comment]
Done
